var neNumber;
var b;
var c;
var d;
var e = [1, 2, 3, 4, 5, 6];
var f = [1, "true", "a", false];
var ColorRed = 0;
var ColorGreen = 1;
var ColorBlue = 2;
var Color;
(function (Color) {
    Color[Color["Red"] = 0] = "Red";
    Color[Color["Green"] = 1] = "Green";
    Color[Color["Blue"] = 2] = "Blue";
})(Color || (Color = {}));
var backgroundColor = Color.Green;
count = 1;
var newMessage = "abc";
message.endsWith("c");
var ebdsWith = message.endsWith("c");
var yetAnother = message.endsWith("c");
